#a workflow to generate a commit a javadoc site for a project

name: generate javadoc

on:
    #when a commit is pushed to main
    push:
        branches:
            - main

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Generate Javadoc
              run: ./gradlew javadoc
            - name: Commit Javadoc
              run: |
              
                git add -f lib/build/docs/javadoc
                git commit -m "Javadoc for ${{ github.sha }}"
                git push origin HEAD:main
            #commit the javadoc folder, the folder has been added to the .gitignore file